package uk.co.bithatch.snake.lib;

public enum Capability {
	BATTERY, BRIGHTNESS, BRIGHTNESS_PER_REGION, DEDICATED_MACRO_KEYS, DPI, EFFECT_PER_REGION, EFFECTS, GAME_MODE,
	KEYBOARD_LAYOUT, MACRO_MODE_MODIFIER, MACROS, MATRIX, POLL_RATE, RIPPLE_RANDOM, RIPPLE_SINGLE,
	STARLIGHT_DUAL, STARLIGHT_RANDOM, STARLIGHT_SINGLE
}
