package uk.co.bithatch.snake.lib;

public enum Capability {
	GAME_MODE, EFFECTS, POLL_RATE, BRIGHTNESS, DPI, BRIGHTNESS_PER_REGION, EFFECT_PER_REGION, BATTERY,
	DEDICATED_MACRO_KEYS, MATRIX, KEYBOARD_LAYOUT, MACRO_MODE_MODIFIER, MACROS, STARLIGHT_DUAL, STARLIGHT_RANDOM,
	STARLIGHT_SINGLE, RIPPLE_RANDOM, RIPPLE_SINGLE
}
