package uk.co.bithatch.snake.lib;

public enum Key {
	APOSTROPHE, BACKSLASH, BACKSPACE, BACKTICK, CAPSLK, COMMA, CTXMENU, DASH, DELETE, DOWNARROW, END,
	ENTER, EQUALS, ESC, FN, FORWARDSLASH, GAMEMODE, HOME, INS, LEFTALT, LEFTARROW, LEFTCTRL, LEFTSHIFT,
	LEFTSQUAREBRACKET, M1, M2, M3, M4, M5, MACROMODE, NP0, NP1, NP2, NP3, NP4, NP5, NP6, NP7, NP8, NP9, NPASTERISK,
	NPDASH, NPFORWARDSLASH, NPPERIOD, NPPLUS, NUMLK, PAGEDOWN, PAGEUP, PAUSE, PERIOD, POUNDSIGN, PRTSCR, RETURN,
	RIGHTALT, RIGHTARROW, RIGHTCTRL, RIGHTSHIFT, RIGHTSQUAREBRACKET, SCRLK, SEMICOLON, SPACE, SUPER, TAB, UPARROW

}
