package uk.co.bithatch.snake.lib;

public enum Key {
	ESC, DASH, EQUALS, BACKSPACE, TAB, LEFTSQUAREBRACKET, RIGHTSQUAREBRACKET, RETURN, LEFTCTRL, SEMICOLON, APOSTROPHE,
	BACKTICK, LEFTSHIFT, POUNDSIGN, COMMA, PERIOD, FORWARDSLASH, RIGHTSHIFT, NPASTERISK, LEFTALT, SPACE, CAPSLK, NUMLK,
	SCRLK, PAUSE, NP7, NP8, NP9, NPDASH, NP4, NP5, NP6, NPPLUS, NP1, NP2, NP3, NP0, PRTSCR, NPPERIOD, BACKSLASH, ENTER,
	RIGHTCTRL, NPFORWARDSLASH, RIGHTALT, HOME, UPARROW, PAGEUP, LEFTARROW, RIGHTARROW, END, DOWNARROW, PAGEDOWN, INS,
	DELETE, SUPER, CTXMENU, M1, M2, M3, M4, M5, FN, GAMEMODE, MACROMODE

}
